### ISSUE TITLE
Why do you roll all the models' parameters together? 

### ISSUE THREAD

**Issue by alexlenail** [siddharth-agrawal/Neural-Tensor-Network#2]
You have this function, [StackToParams](https://github.com/siddharth-agrawal/Neural-Tensor-Network/blob/master/neuralTensorNetwork.py#L63) where you seem to take all the models' parameters and roll them into one parameter, which seems moderately expensive. The only place it seems like you us this representation of your parameters is that allows you to say [this](https://github.com/siddharth-agrawal/Neural-Tensor-Network/blob/master/neuralTensorNetwork.py#L388), which is clean, I admit. But this seems like a lot of overhead to keep the code a little cleaner. And for this cleanliness, I feel like you've lost some readability. Am I missing something? Is there some other reason you chose to wrap all those parameters together?

**Comment by siddharth-agrawal** [comment]
It has been sometime since I wrote this, so I may be a little off. You are right that it makes a code a little cleaner. But the primary reason I did it was to use scipy.optimize.minimize (https://github.com/siddharth-agrawal/Neural-Tensor-Network/blob/master/neuralTensorNetwork.py#L728, https://github.com/siddharth-agrawal/Neural-Tensor-Network/blob/master/neuralTensorNetwork.py#L732). I didn't know any other method of doing that (still don't). Does that make sense? Please let me know if you know a better way of doing this. However, I won't be able to make changes with my current setup (sorry about this).

**Comment by alexlenail** [comment]
No worries about that -- I'm just reimplementing this paper as well, and your implementation is super clear and has provided a valuable guide for me. I'm using tensorflow, which gets the model parameters implicitly, which is nice. I think we will forgo rolling and unrolling the parameters.

**Comment by apogre** [comment]
@zfrenchee Is your implementation with tensorflow available in github?

**Comment by alexlenail** [comment]
https://github.com/dddoss/tensorflow-socher-ntn however would recommend @siddharth-agrawal's implementation, I think it's much cleaner and I'm not sure we ever finally got ours to work. It's not supported.

**Comment by apogre** [comment]
Thanks. I already tried this one. It got stuck with 10th iteration with Freebase data.
Stuck with this issue with this implementation( [(https://github.com/siddharth-agrawal/Neural-Tensor-Network/issues/5)]
